#=================#
#=== BOOK INFO ===#

[book]
  authors = ["IDEDARY"]
  language = "en"
  src = "src"
  title = "Bevy Lunex Documentation"

#============#
#=== HTML ===#

[output.html]
  additional-css = [
    "./theme/css/catppuccin.css",
  ]
  default-theme = "frappe"
  preferred-dark-theme = "mocha"
